### ISSUE TITLE
Multiday events?

### ISSUE THREAD

**Issue by atrus6** [Rawnly/festivities.json#1]
How would one add an entry for a multiday festivity, such as Hanukkah?

**Comment by rawnly** [comment]
I tought something like this 
```json

{
 "christmas": {
   "isPeriod": true,
   "day" :  {
      "start": 24,
      "end": 25
     },
     ...
    }
  }

```

Or with a js function who checks if `christmas.day.start` is true

@atrus6 I'll add in the new release
